# Generated by Django 3.2.20 on 2023-07-14 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("booking", "0001_initial"),
        ("playground", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settingsbooking",
            name="playground",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings_playground",
                to="playground.playground",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="playground",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="playground.playground",
            ),
        ),
    ]
