# Generated by Django 4.2.4 on 2023-09-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("playground", "0003_alter_imageplayground_playground_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("booking", "0003_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="playground",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playground.playground",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="settingsbooking",
            name="playground",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="playground.playground",
            ),
        ),
    ]
