# Generated by Django 4.2.4 on 2023-09-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "booking",
            "0004_alter_booking_playground_alter_booking_user_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="approved",
        ),
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Создан"),
                    (1, "Подтвержден"),
                    (2, "Отменен"),
                    (3, "Завершен"),
                ],
                default=0,
                verbose_name="Статусы резервирования",
            ),
        ),
    ]
