# Generated by Django 4.2.4 on 2023-10-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("owner", "Owner")],
                default="user",
                max_length=5,
            ),
        ),
    ]
