# Generated by Django 4.2.4 on 2023-09-02 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playground", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageplayground",
            name="playground",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="playground.playground",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="playground",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="playground.playground",
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="covering",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="playground.covering",
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="playground",
            name="sports",
            field=models.ManyToManyField(to="playground.sport"),
        ),
    ]
